### ISSUE TITLE
You need a license

### ISSUE THREAD

**Issue by TyNoOutlet** [AbeTGT/TeamService2#1]
Licenses protect work in various ways. If anyone makes a slight modification to this currently, you may lose rights to the content. With a license, you keep rights to the content while still allowing others to use the content.

However, you can't protect people "stealing" or "plagiarizing" (line 11 of module) this module because if the code is open-source as this is, that's not a thing. You're allowing people to do whatever they wish with the code (at the moment, a license adds restrictions). However, you can never stop people from editing the module (line 25). Don't put your code here nor on the Roblox website if you don't want that.

Trust me, you want a license.

**Comment by AbeTGT** [comment]
Alright, thanks for letting me know. You can re-read the original post to see what I have changed.
It is now officially open source.
